# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Faster version of single sow
#' @param
single_sow_cpp <- function(player, B_N, B_S, pit_r, pit_c, direction) {
    .Call(`_mancalaR_single_sow_cpp`, player, B_N, B_S, pit_r, pit_c, direction)
}

